### ISSUE TITLE
Talk Submissions

### ISSUE THREAD

**Issue by atheriel** [gta-r-user-group/gtar#5]
The Meetup group points to the issue tracker in this repository for talk ideas/pitches -- is that still correct?

**Comment by rich-iannone** [comment]
Yes! If you have one, definitely post it here. (I'll create labels to tag talk ideas.)

**Comment by atheriel** [comment]
Do you want to have a single issue for all pitches or have users submit them separately?

**Comment by rich-iannone** [comment]
Separately would be best. Then there would be less confusion about which comments are directed to each submission.

**Comment by atheriel** [comment]
Sure! I'll open a separate issue, then.
